name: Windows builds

on: [push, pull_request]

jobs:
  build_clamav:
    name: Build ClamAV for Windows
    runs-on: windows-latest
    env:
      CHERE_INVOKING:  yes
      CLAM_INST_DIR:   "${{ github.workspace }}/local"
    steps:
      - uses:  actions/checkout@v2

      - name:  Prepare ClamAV cache
        id:    prep-clam
        shell: bash
        run: |
          mkdir -p "${CLAM_INST_DIR}"
          echo "::set-output name=dir::$CLAM_INST_DIR"

      - uses:  actions/cache@v1
        id:    cache-clam
        with:
          path: ${{ steps.prep-clam.outputs.dir }}
          key: clamav-0.102.2-test

      - name:  Install MSYS2
        if:    steps.cache-clam.outputs.cache-hit != 'true'
        run:   choco install msys2 --no-progress

      - name:  Build, install, and test
        if:    steps.cache-clam.outputs.cache-hit != 'true'
        shell: python scripts\msys-bash.py {0}
        run: |
          ./scripts/list-build-dependencies.sh -m msys2 -c gcc | xargs pacman -S --noconfirm
          pacman -S --noconfirm libcurl-devel
          ./contrib/clamav/build.sh
          ldd ./local/bin/clamscan
          ./local/bin/clamscan --heuristic-scan-precedence=yes --recursive --infected .
          tar -czvf local.tar.gz local

      - name: Upload installation package
        uses: actions/upload-artifact@v1
        with:
          name: local
          path: local.tar.gz
