name: Windows builds

on: [push, pull_request]

jobs:
  build_clam:
    name: AV Scan
    runs-on: windows-latest
    env:
      CHERE_INVOKING: yes
      VT_CLI_DIR:  "${{ github.workspace }}/vt-cli"
    steps:
      - name:  Prepare VT CLI cache
        id:    prep-vt-cli
        shell: bash
        run: |
          mkdir -p "${VT_CLI_DIR}"
          echo "::set-output name=dir::$VT_CLI_DIR"

      - uses:  actions/cache@v1
        id:    cache-vt-cli
        with:
          path: ${{ steps.prep-vt-cli.outputs.dir }}
          key: vt-cli-1

      - name:  Build
        if:    steps.cache-vt-cli.outputs.cache-hit != 'true'
        shell: bash
        run: |
          set -x
          git clone https://github.com/VirusTotal/vt-cli.git
          cd vt-cli
          VERSION="$(git describe)"
          LDFLAGS="-X github.com/VirusTotal/vt-cli/cmd.Version=${VERSION}"
          go build -ldflags "${LDFLAGS}" -o ./build/vt ./vt/main.go
          ./build/vt --help
